### ISSUE TITLE
Arch does no longer boot after setup

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#22]
The desktop loading fails with the current master branch version. Mabybe we should roll back to a working version and try out new stuff in separate branches. Having a non-working version in the current master branch sucks, especially when you expect you can do a quick reinstall just to find out, nothing works.

**Comment by GPMueller** [comment]
ok then we should do a rebase or whatever is appropriate to move the current changeset to a 'develop'.

It would make sense to improve the autorun script, to be able to pass arguments like -develop or -v1.1 in order to choose the desired version.
Otherwise, it would be a pain to test committed changes

Do we
a) only make commits to master by merging from develop when making a new release
b) merge from develop regularly and tag a few versions as releases every now and then

**Comment by NOhs** [comment]
I like the idea of the adopted autorun script to take a branch name.
We should also have a branch for every feature we are working on, so that working features can be integrated faster into the master branch, see also https://guides.github.com/introduction/flow/. Which means that we do not only merge when we release a new version.

**Comment by GPMueller** [comment]
![image](https://cloud.githubusercontent.com/assets/20167491/21245130/17fa52e2-c321-11e6-99dd-731cc50ee085.png)

**Comment by NOhs** [comment]
![grafik](https://cloud.githubusercontent.com/assets/20553080/21245311/1432e9a2-c322-11e6-97a6-4fe7b29ad0b3.png)

**Comment by NOhs** [comment]
Ok. An issue seems to be that plasma does not by itself pulls some required xorg-server packages
https://github.com/sddm/sddm/issues/605#issuecomment-275938830

**Comment by NOhs** [comment]
Issue solved with commit 108fe12123797fd08c8978ebbc9f0180c5a9261d
